# Creating array

In [4]:
import array

my_array = array.array('i')           #i stand for integer
print(my_array)
my_array1 = array.array('i',[1,2,3,4])
print(my_array1)

array('i')
array('i', [1, 2, 3, 4])


In [2]:
import numpy as np

np_array = np.array([], dtype=int)         #empty array
print(np_array)
np_array1 = np.array([1,2,3,4])
print(np_array1)

[]
[1 2 3 4]


# Insertion in array

In [9]:
import array

my_array = array.array('i',[1,2,3,4,5])           
print(my_array)
my_array.insert(5,6)              #Here 5 is the index value
print(my_array)

array('i', [1, 2, 3, 4, 5])
array('i', [1, 2, 3, 4, 5, 6])


# Array traversal

In [10]:
def traverse_array(array):
    for i in array:
        print(i)

traverse_array(my_array)

1
2
3
4
5
6


# Access element in array

In [15]:
def accessElement(array,index):
    if index >= len(array):
        print("There is no such element in the array.")
    else:
        print(array[index])
    
accessElement(my_array,6)

There is no such element in the array.


# Searching for element in array

In [17]:
def linear_search(arr,target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1
    
linear_search(my_array,5)

4

# Deleting element in array

In [18]:
my_array.remove(6)                        #worst case time cpmplexity O(n)
print(my_array)                     

array('i', [1, 2, 3, 4, 5])


# One dimension array practice


In [37]:
from array import *

# 1.Create an array and traverse.

print('Step:1')
my_array = array('i',[1,2,3,4,5])
for i in my_array:
    print(i)

# 2.Access individual element through indexes.

print('Step:2')
print(my_array[4])

# 3.Append any value to the array using append() method.

print('Step:3')
my_array.append(6)
print(my_array)

# 4.Insert value in array using insert() method.

print('Step:4')
my_array.insert(6,7)
print(my_array)

# 5.Extend python array using extend() method.

print('Step:5')
my_array2 = array('i',[10,11,12])
my_array.extend(my_array2)
print(my_array)

# 6.Add items from list into array using fromlist() method.

print('Step:6')
templist = [20,21,22]
my_array.fromlist(templist)
print(my_array)

# 7.Remove any array element using remove() method.

print('Step:7')
my_array.remove(6)
print(my_array)

# 8.Remove last array element using pop() method.

print('Step:8')
my_array.pop()
print(my_array)

# 9.Fetch any element through its index using index() method.

print('Step:9')
print(my_array.index(20))

# 10.Reverse the python array using reverse() method.

print('Step:10')
my_array.reverse()
print(my_array)

# 11.Get array buffer information using buffer_info() method.

print('Step:11')
print(my_array.buffer_info())

# 12.Check for number of occurence using count() method.

print('Step:12')
print(my_array.count(3))

# 13.Convert array to list using tolist() method.

print('Step:13')
print(my_array.tolist())

# 14.Slice element from array.

print('Step:14')
print(my_array[1:4])

Step:1
1
2
3
4
5
Step:2
5
Step:3
array('i', [1, 2, 3, 4, 5, 6])
Step:4
array('i', [1, 2, 3, 4, 5, 6, 7])
Step:5
array('i', [1, 2, 3, 4, 5, 6, 7, 10, 11, 12])
Step:6
array('i', [1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 20, 21, 22])
Step:7
array('i', [1, 2, 3, 4, 5, 7, 10, 11, 12, 20, 21, 22])
Step:8
array('i', [1, 2, 3, 4, 5, 7, 10, 11, 12, 20, 21])
Step:9
9
Step:10
array('i', [21, 20, 12, 11, 10, 7, 5, 4, 3, 2, 1])
Step:11
(2408572231280, 11)
Step:12
1
Step:13
[21, 20, 12, 11, 10, 7, 5, 4, 3, 2, 1]
Step:14
array('i', [20, 12, 11])


# Two dimensional array

## Insertion in two dimensional array

In [45]:
import numpy as np

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)
newtwoDArray = np.insert(twoDArray,0,[[1,2,3,4]],axis=0)            #axis=0 for adding as row & axis=1 for adding as coloumn
print(newtwoDArray)
newtwoDArray = np.append(twoDArray,[[5,6,7,8]],axis=0)            
print(newtwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 5  6  7  8]]


## Access element in 2D array

In [47]:
def accessElement(array,rowindex,colindex):
    if rowindex >= len(array) or colindex >= len(array[0]):
        print("Incorrect Index.")
    else:
        print(array[rowindex][colindex])

accessElement(twoDArray,0,2)

10


## Traversing in 2D array

In [49]:
def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

traverseTDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


## Searching in 2D array

In [55]:
def searchTDArray(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j]==value:
                return 'The value is located at index '+str(i)+','+str(j)
    return 'The element is not found.'

searchTDArray(twoDArray,12)
    

'The value is located at index 2,0'

## Deleting a row or column in 2D array

In [56]:
newTDArray = np.delete(twoDArray,0,axis=0)           #delete() method will store new 2D array so time & space complexity will be O(mn)
print(newTDArray)

[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
